development:
  adapter: postgresql
  encoding: unicode
  database: micropost_development
  pool: 5
  username: thanhnguyen
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: micropost_test
  pool: 5
  username: thanhnguyen
  password:
